In [5]:
element = 'oxygen'
print('first three characters:', element[-1])
print('last three characters:', element[-2])

first three characters: n
last three characters: e


In [6]:
element = 'oxygen'
print(element[1:-1]) #cuts out the first(number of) word and (-) cuts the word the behind if ':' is present

xyge


In [7]:
element = 'oxygen'
print('last three characters:', element[-3:]) #keeps the last 3 words(counts from the nehind and prints it)
element = 'carpentry'
print('last three characters:', element[-3:])
element = 'clone'
print('last three characters:', element[-3:])
element = 'hi'
print('last three characters:', element[-3:])

last three characters: gen
last three characters: try
last three characters: one
last three characters: hi


In [8]:
import numpy

A = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

D = numpy.hstack((A[:, :1], A[:, -1:]))
print('D = ')
print(D)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
D = 
[[1 3]
 [4 6]
 [7 9]]
